name: stats update

on:
  schedule:
    - cron: '0 0 * * *' # every 12 hours
  push:
    branches:
      - main
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Profile Readme Stats
      uses: teoxoy/profile-readme-stats@v3
      with:
        token: ${{ secrets.USER_TOKEN }}
    - name: Update README.md
      shell: bash
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add *.md
            git commit -m "Update README.md"
            git push
        fi
